using System;
using System.IO;

namespace TiaAgent.AddIn.Bridge;

/// <summary>
/// Configuration for the Bridge HTTP client.
/// Reads from %LOCALAPPDATA%\TiaAgent\addin.json.
/// </summary>
public sealed class BridgeClientConfig
{
    private static readonly string ConfigDir = Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
        "TiaAgent");

    private static readonly string ConfigFile = Path.Combine(ConfigDir, "addin.json");

    public string BridgeBaseUrl { get; set; } = "http://127.0.0.1:43119";
    public int RequestTimeoutSeconds { get; set; } = 15;
    public int PollingIntervalMilliseconds { get; set; } = 500;
    public int TaskTimeoutSeconds { get; set; } = 300;

    /// <summary>
    /// Bearer token for Bridge authentication. Read from %LOCALAPPDATA%\TiaAgent\bridge.token.
    /// Generated by the Bridge on first startup; shared via file for Add-In discovery.
    /// </summary>
    public string? AuthToken { get; private set; }

    public static BridgeClientConfig Load()
    {
        var config = new BridgeClientConfig();

        try
        {
            if (File.Exists(ConfigFile))
            {
                var json = File.ReadAllText(ConfigFile);
                config = ParseJson(json);
            }
            else
            {
                // Fallback: try runtime discovery from supervisor manifest
                config = TryLoadFromRuntimeManifest() ?? config;
            }
        }
        catch
        {
            // Swallow — use defaults
        }

        config.AuthToken = LoadAuthToken();

        return config;
    }

    /// <summary>
    /// Attempts to load Bridge configuration from the runtime manifest
    /// published by the supervisor. Used when addin.json is not present.
    /// </summary>
    private static BridgeClientConfig? TryLoadFromRuntimeManifest()
    {
        try
        {
            var manifestPath = Path.Combine(ConfigDir, "runtime", "runtime.json");
            if (!File.Exists(manifestPath))
                return null;

            var json = File.ReadAllText(manifestPath);
            if (string.IsNullOrWhiteSpace(json))
                return null;

            // Parse manifest to get bridge port
            var bridgePort = ExtractIntValue(json, "port", "bridge");
            var bridgeHost = ExtractNestedStringValue(json, "host", "bridge");
            var bridgeStatus = ExtractNestedStringValue(json, "status", "bridge");

            // Only use if bridge is healthy
            if (bridgeStatus != "healthy" || bridgePort <= 0)
                return null;

            var host = bridgeHost ?? "127.0.0.1";
            return new BridgeClientConfig
            {
                BridgeBaseUrl = $"http://{host}:{bridgePort}"
            };
        }
        catch
        {
            return null;
        }
    }

    private static int? ExtractIntValue(string json, string key, string? nestedKey = null)
    {
        var search = "\"" + key + "\"";
        var idx = json.IndexOf(search, StringComparison.OrdinalIgnoreCase);
        if (idx < 0) return null;

        idx = json.IndexOf(':', idx + search.Length);
        if (idx < 0) return null;

        idx++;
        while (idx < json.Length && json[idx] == ' ') idx++;

        if (idx >= json.Length) return null;

        var start = idx;
        while (idx < json.Length && char.IsDigit(json[idx])) idx++;

        if (idx > start && int.TryParse(json.Substring(start, idx - start), out var value))
            return value;

        return null;
    }

    private static string? ExtractNestedStringValue(string json, string key, string nestedKey)
    {
        // Find the nested object first (e.g., "bridge": { ... })
        var nestedSearch = "\"" + nestedKey + "\"";
        var nestedIdx = json.IndexOf(nestedSearch, StringComparison.OrdinalIgnoreCase);
        if (nestedIdx < 0) return null;

        // Find the opening brace
        var braceIdx = json.IndexOf('{', nestedIdx);
        if (braceIdx < 0) return null;

        // Find the matching closing brace
        var depth = 0;
        var start = braceIdx;
        for (var i = braceIdx; i < json.Length; i++)
        {
            if (json[i] == '{') depth++;
            else if (json[i] == '}')
            {
                depth--;
                if (depth == 0)
                {
                    var nestedJson = json.Substring(start, i - start + 1);
                    return ExtractValue(nestedJson, key);
                }
            }
        }

        return null;
    }

    /// <summary>
    /// Reads the shared bearer token from %LOCALAPPDATA%\TiaAgent\bridge.token.
    /// The Bridge writes this file on startup; the Add-In reads it to authenticate.
    /// </summary>
    private static string? LoadAuthToken()
    {
        try
        {
            var tokenFile = Path.Combine(ConfigDir, "bridge.token");
            if (!File.Exists(tokenFile))
                return null;

            var token = File.ReadAllText(tokenFile).Trim();
            return string.IsNullOrEmpty(token) ? null : token;
        }
        catch
        {
            return null;
        }
    }

    private static BridgeClientConfig ParseJson(string json)
    {
        var config = new BridgeClientConfig();

        var baseUrl = ExtractValue(json, "bridgeBaseUrl");
        if (baseUrl != null)
            config.BridgeBaseUrl = baseUrl;

        var timeout = ExtractIntValue(json, "requestTimeoutSeconds");
        if (timeout.HasValue)
            config.RequestTimeoutSeconds = timeout.Value;

        var polling = ExtractIntValue(json, "pollingIntervalMilliseconds");
        if (polling.HasValue)
            config.PollingIntervalMilliseconds = polling.Value;

        var taskTimeout = ExtractIntValue(json, "taskTimeoutSeconds");
        if (taskTimeout.HasValue)
            config.TaskTimeoutSeconds = taskTimeout.Value;

        return config;
    }

    private static string? ExtractValue(string json, string key)
    {
        var search = "\"" + key + "\"";
        var idx = json.IndexOf(search, StringComparison.OrdinalIgnoreCase);
        if (idx < 0) return null;

        idx = json.IndexOf(':', idx + search.Length);
        if (idx < 0) return null;

        idx++;
        while (idx < json.Length && json[idx] == ' ') idx++;

        if (idx >= json.Length) return null;

        if (json[idx] == '"')
        {
            var start = idx + 1;
            var end = json.IndexOf('"', start);
            if (end < 0) return null;
            return json.Substring(start, end - start);
        }

        return null;
    }

    private static int? ExtractIntValue(string json, string key)
    {
        var search = "\"" + key + "\"";
        var idx = json.IndexOf(search, StringComparison.OrdinalIgnoreCase);
        if (idx < 0) return null;

        idx = json.IndexOf(':', idx + search.Length);
        if (idx < 0) return null;

        idx++;
        while (idx < json.Length && json[idx] == ' ') idx++;

        if (idx >= json.Length) return null;

        var start = idx;
        while (idx < json.Length && char.IsDigit(json[idx])) idx++;

        if (idx > start && int.TryParse(json.Substring(start, idx - start), out var value))
            return value;

        return null;
    }
}
